### ISSUE TITLE
Fix drupal message when I save the name of the list without editing it.

### ISSUE THREAD

**Issue by stijnswaanen** [district09/drupal_module_culturefeed-lists#11]
When I edit the name of the list and click save without actually editing the name, I get a drupal message which says "No changes for list %name."

That's because there is in culturefeed_lists.admin.inc on line 309 the following:
`drupal_set_message(t('No changes for list %name.', $message_args), 'status');`

However the $message_args array doesn't contain the %name value. It only contains %name_new, %path_new, %name_old, %path_old.

This issue will be solved if we change the above line with:
`drupal_set_message(t('No changes for list %name_old.', $message_args), 'status');`

**Comment by stijnswaanen** [comment]
Pull request: #12

**Comment by zero2one** [comment]
Merged See PR #12
